### ISSUE TITLE
[BUG] PointSelector and Annotations width some object at the first render

### ISSUE THREAD

**Issue by mikyweb** [Secretmapper/react-image-annotation#1]
Hello, and compliments !, the component is very helpful.

There is a bug.
If you use the PointSelector and pass to the component an array of annotations already from the first render, the component presents a bug.

```
> PointSelector.js?9742:14 Uncaught TypeError: Cannot read property 'width' of undefined
>     at marginToPercentage (PointSelector.js?9742:14)
```

I solved the problem by setting the annotations property only to the componentDidMount.
I imagine the problem is timing.

**Comment by Secretmapper** [comment]
Fixed w/ https://github.com/Secretmapper/react-image-annotation/commit/1cbbf7134c5c43a53f2129591bc2462efc9c22f1

Thanks for the bug report!
