### ISSUE TITLE
Portrait images get transformed into landscape images

### ISSUE THREAD

**Issue by srinivas-alva-gc** [Secretmapper/react-image-annotation#30]
When I upload portrait image its automatically gets transformed into landscape (at preview).

**Comment by Secretmapper** [comment]
Hello @srinivas-alva-gc would you be able to make a reproduction/sample code?

**Comment by srinivas-alva-gc** [comment]
Sorry! I won't be able to help you regarding this issue. I just started learning react-native.

**Comment by Secretmapper** [comment]
Unfortunately I won't be able to help without sample code :(

Note that react-image-annotation does apply some default style (100% width) so make sure the correct aspect ratio is applied to the container
