### ISSUE TITLE
Close/Abort Annotation

### ISSUE THREAD

**Issue by JonathanKolnik** [Secretmapper/react-image-annotation#5]
Awesome library!

Wondering if there is a prop or workaround for closing/not submitting/aborting an annotation in progress?

Thanks!

**Comment by Secretmapper** [comment]
Hello @JonathanKolnik !

You should be able to pass a custom component through `renderEditor` that has a 'Cancel' button, which would clear the annotation object.

Let me know if this works for you!

**Comment by Secretmapper** [comment]
Closing this issue. Please feel free to comment/open another one if the solution does not work.
