### ISSUE TITLE
More examples in demo

### ISSUE THREAD

**Issue by AdamGerthel** [Secretmapper/react-image-annotation#6]
I haven't tried the solution from #5, but I would love to see a "cancel" button in the demo, or at least some form of cancellation. I tried clicking outside the annotation area (the overlay) several times before I realised that I couldn't easily cancel. 

I also think it would feel more natural to have to click and drag to start a new annotation area instead of just click, since it's quite easy to mis-click and start a new annotation (which there is currently no way to cancel). I think it's fair to say that that's how most graphics software as well as document writer software (Word, Pages etc.) manages boxes of different kinds.

**Comment by Secretmapper** [comment]
@AdamGerthel Thanks for the feedback. I agree with changing annotation from click to drag to start, I'll add it in the next version.

**Comment by Secretmapper** [comment]
Fixed by ec523c544a32d12661f50f5a0a21bfff46ecfffd
