### ISSUE TITLE
disableEditor true buggy

### ISSUE THREAD

**Issue by HRK44** [Secretmapper/react-image-annotation#9]
When I use ``disableEditor={true}``, I guess it works like intended (doesn't show the editor) BUT I can't 'validate' the selection anymore since there is no 'submit'.

Is this intended behavior, or is it a bug? From an user perspective, what I think when I disable the editor, is that the selection is automatically validated upon mouse release.

Thanks

**Comment by Secretmapper** [comment]
Sorry for the late reply! Yes this is intended behavior - the only thing it would do is it disables the editor.

To achieve something like this (auto submit), pass a component in `renderEditor` that calls `onSubmit` on mount.
